name: 02:AWS IVS Inspector - AWS Infra

on: workflow_dispatch
  # push:
  #   branches:
  #     - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: terraform_admin
    env: 
      TF_LOG: INFO
      TF_VAR_account_id: ${{ secrets.ACCOUNT_ID }}
      TF_VAR_region: ap-south-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
      AWS_AMPLIFY_APP_ID: ${{ vars.AMPLIFY_APP_ID }}

    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v2

      - name: Setup Terraform with specific version on the runner
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.2
        
      - name: Terraform Init
        id: init
        run: |
          cd terraform-infra
          terraform fmt
          terraform init \
           -backend-config="bucket=${{ secrets.BUCKET_TF_STATE }}" \
           -backend-config="key=infra/$TF_VAR_region/terraform.tfstate" \
           -backend-config="region=us-west-2"

      - name: Terraform Validate
        id: validate
        run: |
          cd terraform-infra
          terraform validate

      - name: Terraform Plan
        id: plan
        run: |
          cd terraform-infra
          terraform plan -no-color -input=false
        continue-on-error: true

      - name: Terraform Apply
        id: apply
        if: github.ref == 'refs/heads/main'
        run: |
          cd terraform-infra
          terraform apply -auto-approve -input=false

      - name: Add Amplify Env Var 
        run: |
          echo "api_ids: ${{ steps.apply.outputs.api_ids }}"
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID 
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY 
          aws configure set region "ap-south-1"
          aws amplify update-app --app-id $AWS_AMPLIFY_APP_ID --environment-variables ap_south_1_api_ids=${{ steps.apply.outputs.api_ids }}
