name: 02:AWS Infra ap-south-1

on: #workflow_dispatch
  push:
    branches:
      - dev

env:
  TF_VAR_region: "ap-south-1"
  TF_VAR_project_name: ${{ secrets.IVS_PROJECT_NAME }}
  TF_VAR_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
  TF_LOG: INFO
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_S3_BUCKET_FOR_TF_STATE: ${{ secrets.AWS_S3_BUCKET_FOR_TF_STATE }}
  AWS_S3_BUCKET_FOR_TF_STATE_REGION: ${{ secrets.AWS_S3_BUCKET_FOR_TF_STATE_REGION }}
  AWS_AMPLIFY_APP_ID: ${{vars.AMPLIFY_APP_ID}}
  AWS_AMPLIFY_APP_REGION: "us-east-2"
  tmpJson: $(mktemp)
  tmpCurrentEnvVars: $(mktemp)
  envVarsPath: ./web-application/.env

jobs:
  terraform_for_infra:
    runs-on: ubuntu-latest
    environment: ivs_inspector_backend

    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v4

      - name: Setup Terraform with specific version on the runner
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.2

      - name: Terraform Init
        id: init
        run: |
          cd terraform-infra
          terraform fmt
          terraform init \
           -backend-config="bucket=$AWS_S3_BUCKET_FOR_TF_STATE" \
           -backend-config="key=infra/$TF_VAR_region/terraform.tfstate" \
           -backend-config="region=$AWS_S3_BUCKET_FOR_TF_STATE_REGION" \
           -reconfigure

      # - name: Terraform Validate
      #   id: validate
      #   run: |
      #     cd terraform-infra
      #     terraform validate

      # - name: Terraform Plan
      #   id: plan
      #   run: |
      #     cd terraform-infra
      #     terraform plan -no-color -input=false
      #   continue-on-error: true

      # - name: Terraform Apply
      #   id: apply
      #   run: |
      #     cd terraform-infra
      #     terraform apply -auto-approve -input=false

      - name: Terraform Output
        id: output
        run: |
          cd terraform-infra
          echo "api_ids=$(terraform output -json api_ids)" >> $GITHUB_OUTPUT

    outputs:
      api_ids: ${{ steps.output.outputs.api_ids }}

  update_webapp_repo_env_vars:
    name: "Adding API IDs into Env Var file"
    runs-on: ubuntu-latest
    environment: ivs_inspector_backend
    needs: terraform_for_infra
    steps:
      - name: Checkout the repositoring to the runner
        uses: actions/checkout@v4

      - name: build API data
        id: build_api_data
        run: |
          api_values=$(jq --arg region "$TF_VAR_region" '.[$region]' <<< "${{needs.terraform_for_infra.outputs.api_ids}}")
          jq --arg region "$TF_VAR_region" --arg values "$api_values" '$region = $values' "$envVarsPath" > "$tmpJson" && mv "$tmpJson" "$envVarsPath"
          cat $envVarsPath

      - name: Git Commit
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add $envVarsPath
          git commit --allow-empty -m "update environment variables"

      - name: Git Push
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: true

  update_amplify_env_vars:
    name: "Adding API IDs into Amplify Env Var"
    runs-on: ubuntu-latest
    environment: ivs_inspector_backend
    needs: terraform_for_infra
    steps:
      - name: Checkout the repositoring to the runner
        uses: actions/checkout@v4

      # - name: Install Amplify CLI
      #   run: |
      #     # cd web-application
      #     npm install -g @aws-amplify/cli
      #     # ls -lh

      #     ENV_NAME="backend"

      #     VUECONFIG="{\
      #     \"SourceDir\":\"src\",\
      #     \"DistributionDir\":\"dist/spa\",\
      #     \"BuildCommand\":\"npm run build\",\
      #     \"StartCommand\":\"npm run start\"\
      #     }"

      #     FRONTEND="{\
      #     \"frontend\":\"javascript\",\
      #     \"framework\":\"vue\",\
      #     \"config\":$VUECONFIG\
      #     }"

      #     # note: session token cannot be passed in here
      #     AWSCLOUDFORMATIONCONFIG="{\
      #     \"configLevel\":\"project\",\
      #     \"useProfile\":false,\
      #     \"accessKeyId\":\"$AWS_ACCESS_KEY_ID\",\
      #     \"secretAccessKey\":\"$AWS_SECRET_ACCESS_KEY\",\
      #     \"region\":\"ap-south-1\"\
      #     }"

      #     AMPLIFY="{\
      #     \"projectName\":\"Inspector\",\
      #     \"envName\":\"$ENV_NAME\",\
      #     \"defaultEditor\":\"code\"\
      #     }"

      #     PROVIDERS="{\
      #     \"awscloudformation\":$AWSCLOUDFORMATIONCONFIG\
      #     }"

      #     # echo "Initializing Amplify project for env: $ENV_NAME"

      #     amplify init \
      #     --amplify $AMPLIFY \
      #     --frontend $FRONTEND \
      #     --providers $PROVIDERS \
      #     --yes

      #     # echo "Pull Amplify project for env: $ENV_NAME"
      #     # amplify pull --appId $AWS_AMPLIFY_APP_ID --providers $PROVIDERS

      #     # # echo "amplify hosting add for env: $ENV_NAME"
      #     # # amplify add hosting

      #     # echo "Publish Amplify project for env: $ENV_NAME"
      #     # amplify publish --appId $AWS_AMPLIFY_APP_ID --providers $PROVIDERS

      # - name: Configure Amplify
      #   run: |
      #     amplify configure --appId $AWS_AMPLIFY_APP_ID --yes
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      #     AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

      - name: amplify env vars update using AWS CLI
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region $AWS_AMPLIFY_APP_REGION

          amplify_app=$(aws amplify get-app --app-id $AWS_AMPLIFY_APP_ID)
          # amplify_app=$(python3 -c 'import json,sys;JSON=json.load(sys.stdin);print(JSON["app"]["environmentVariables"]);' <<< $(aws amplify get-app --app-id $AWS_AMPLIFY_APP_ID))
          echo $amplify_app

          jq '.app.environmentVariables' <<< "$amplify_app" > $tmpCurrentEnvVars
          echo $tmpCurrentEnvVars
          api_values=$(jq --arg region "$TF_VAR_region" '.[$region]' <<< "${{needs.terraform_for_infra.outputs.api_ids}}")
          api_values=$(echo $api_values | jq -c | jq -R)
          echo $api_values
          jq --arg region "$TF_VAR_region" --arg values "$api_values" '$region = $values' "$tmpCurrentEnvVars" > "$tmpJson" && mv "$tmpJson" "$tmpCurrentEnvVars"
          echo $tmpCurrentEnvVars
          cat $tmpCurrentEnvVars

          aws amplify update-app --app-id $AWS_AMPLIFY_APP_ID --environment-variables $TF_VAR_region="$tmpCurrentEnvVars"

      # - name: Add env var to Amplify
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      #     AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      #   run: |
      #     api_values=$(jq --arg region "$TF_VAR_region" '.[$region]' <<< "${{needs.terraform_for_infra.outputs.api_ids}}")
      #     api_values=$(echo $api_values | jq -c | jq -R)
      #     echo $api_values
      #     # amplify pull --appId $AWS_AMPLIFY_APP_ID --envName backend
      #     # amplify publish --appId $AWS_AMPLIFY_APP_ID --branch ${{ github.ref_name }} --envName backend
