name: 03:AWS IVS Inspector - Web Application

on: workflow_dispatch
  # push:
  #   branches:
  #     - main

jobs:
  web-app:
    runs-on: ubuntu-latest
    environment: terraform_admin
    env:
      TF_LOG: INFO
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_AMPLIFY_APP_ID: ${{vars.AMPLIFY_APP_ID}}
    steps:
      - name: Checkout the repositoring to the runner
        uses: actions/checkout@v3

      - name: Configure AWS CLI
        run: |
          cd web-application
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID 
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY 
          aws configure set region "ap-south-1"
          aws amplify start-job --app-id $AWS_AMPLIFY_APP_ID --branch-name ivs --job-type RELEASE --commit-message "commit from GitHub"
        # shell: bash

      # - name: Install Amplify CLI
      #   run: |
      #     cd web-application
      #     npm install -g @aws-amplify/cli
      #     ls -lh

      #     ENV_NAME="backend"

      #     VUECONFIG="{\
      #     \"SourceDir\":\"src\",\
      #     \"DistributionDir\":\"dist/spa\",\
      #     \"BuildCommand\":\"npm run build\",\
      #     \"StartCommand\":\"npm run start\"\
      #     }"

      #     FRONTEND="{\
      #     \"frontend\":\"javascript\",\
      #     \"framework\":\"vue\",\
      #     \"config\":$VUECONFIG\
      #     }"

      #     # note: session token cannot be passed in here
      #     AWSCLOUDFORMATIONCONFIG="{\
      #     \"configLevel\":\"project\",\
      #     \"useProfile\":false,\
      #     \"accessKeyId\":\"$AWS_ACCESS_KEY_ID\",\
      #     \"secretAccessKey\":\"$AWS_SECRET_ACCESS_KEY\",\
      #     \"region\":\"ap-south-1\"\
      #     }"

      #     AMPLIFY="{\
      #     \"projectName\":\"Inspector\",\
      #     \"envName\":\"$ENV_NAME\",\
      #     \"defaultEditor\":\"code\"\
      #     }"

      #     PROVIDERS="{\
      #     \"awscloudformation\":$AWSCLOUDFORMATIONCONFIG\
      #     }"

      #     # echo "Initializing Amplify project for env: $ENV_NAME"

      #     # amplify init \
      #     # --amplify $AMPLIFY \
      #     # --frontend $FRONTEND \
      #     # --providers $PROVIDERS \
      #     # --yes

      #     echo "Pull Amplify project for env: $ENV_NAME"
      #     amplify pull --appId $AWS_AMPLIFY_APP_ID --providers $PROVIDERS

      #     # echo "amplify hosting add for env: $ENV_NAME"
      #     # amplify add hosting

      #     echo "Publish Amplify project for env: $ENV_NAME"
      #     amplify publish --appId $AWS_AMPLIFY_APP_ID --providers $PROVIDERS

      # - name: Configure Amplify
      #   run: |
      #     amplify configure --appId $AWS_AMPLIFY_APP_ID --yes
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      #     AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

      # - name: Deploy to Amplify
      #   run: |
      #     amplify pull --appId $AWS_AMPLIFY_APP_ID --envName backend
      #     amplify publish --appId $AWS_AMPLIFY_APP_ID --branch ivs --envName backend
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      #     AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}


    # strategy:
    #   matrix:
    #     node-version: [10.x]

    # steps:
    # - uses: actions/checkout@v1

    # - name: use node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v1
    #   with:
    #     node-version: ${{ matrix.node-version }}

    # - name: configure amplify
    #   uses: MorFix/amplify-cli-action@0.4.5
    #   with:
    #     amplify_command: configure
    #     amplify_env: prod
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     AWS_REGION: us-east-1

    # - name: install, build and test
    #   run: |
    #     npm install
    #     # build and test
    #     npm run build
    #     npm run test
    
    # - name: deploy
    #   uses: MorFix/amplify-cli-action@0.4.5
    #   with:
    #     amplify_command: publish
    #     amplify_env: prod
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     AWS_REGION: us-east-1