name: 04:test

on: #workflow_dispatch
  push:
    branches:
      - main

jobs:
  web-app:
    runs-on: ubuntu-latest
    environment: terraform_admin
    env:
      TF_LOG: INFO
      GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_AMPLIFY_APP_ID: ${{vars.AMPLIFY_APP_ID}}
    steps:
      - name: Checkout the repositoring to the runner
        uses: actions/checkout@v4

      # - name: test gh cli

      #   run: |
      #     gh variable set test_key --body "test_value1" --env terraform_admin

      # - name: test aws cli for amplify
      #   env:
      #     test_json: "{account_id: 123, api: 456}"
      #   run: |
      #     cd web-application
      #     aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID 
      #     aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY 
      #     aws configure set region "ap-south-1"
      #     aws amplify update-app --app-id $AWS_AMPLIFY_APP_ID --enable-branch-auto-build --environment-variables '{"account_id": "123", "api": "456"}'

      - name: test aws cli for amplify deployment
        env:
          test_json: "{account_id: 123, api: 456}"
        run: |
          cd web-application
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID 
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY 
          aws configure set region "ap-south-1"
          aws amplify create-deployment --app-id $AWS_AMPLIFY_APP_ID --branch-name ivs