name: 04:AWS Infra & Amplify destroy

on: workflow_dispatch

env:
  TF_VAR_region: "us-east-1"
  AWS_AMPLIFY_DEPLOYED_REGION: "us-east-2"
  TF_VAR_repository: ${{ github.server_url }}/${{ github.repository }}
  TF_VAR_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
  TF_VAR_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
  TF_LOG: INFO
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  AWS_S3_BUCKET_FOR_TF_STATE: ${{ secrets.AWS_S3_BUCKET_FOR_TF_STATE }}

jobs:
  terraform_for_infra:
    runs-on: ubuntu-latest
    environment: terraform_admin

    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v4

      - name: Setup Terraform with specific version on the runner
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.2

      - name: Terraform Init
        id: init
        run: |
          cd terraform-infra
          terraform fmt
          terraform init \
           -backend-config="bucket=$AWS_S3_BUCKET_FOR_TF_STATE" \
           -backend-config="key=infra/$TF_VAR_region/terraform.tfstate" \
           -backend-config="region=us-west-2" \
           -reconfigure

      - name: Terraform Destroy
        id: destroy
        run: |
          cd terraform-infra
          terraform destroy -auto-approve -input=false

  terraform_for_amplify:
    runs-on: ubuntu-latest
    environment: terraform_admin

    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v4

      - name: Setup Terraform with specific version on the runner
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.2

      - name: Terraform Init
        id: init
        run: |
          cd terraform-amplify
          terraform fmt
          terraform init \
           -backend-config="bucket=$AWS_S3_BUCKET_FOR_TF_STATE" \
           -backend-config="key=amplify/$AWS_AMPLIFY_DEPLOYED_REGION/terraform.tfstate" \
           -backend-config="region=us-west-2" \
           -reconfigure

      - name: Terraform Destroy
        id: destroy
        run: |
          cd terraform-amplify
          terraform destroy -auto-approve -input=false
