name: IVS Inspector Prerequisites Deployment Pipeline with GitHub Actions

on: 
  workflow_dispatch:
    account_id:
      description: 'Provide Account ID'     
      required: true
      default: 'account_id'
    branch:
      description: 'Provide Region'     
      required: true
      default: 'region'
    project_name:
      description: 'Provide Project Name'     
      required: true
      default: 'project_name'

env:
  TF_LOG: INFO
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: terraform_admin
    defaults:
      run:
        shell: bash
        working-directory: ./terraform
    steps:
      - name: Checkout the repositoring to the runner
        uses: actions/checkout@v3

      - name: Setup Terraform with specific version on the the runner
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.2

      - name: Terraform init
        id: init
        run: terraform init -backend-config="./backend-configs/ap-south-1.conf"

      - name: Terraform format
        id: fmt
        run: terraform fmt -check

      - name: Terraform validate
        id: validate
        run: terraform validate

      - name: Terraform plan
        id: plan
        run: terraform plan -no-color -input=false
        continue-on-error: true

      - name: Terraform apply
        id: apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -input=false        