name: AWS IVS Inspector Infra

on: #workflow_dispatch
  push:
    branches:
      - main
  # workflow_dispatch:
    # region:
    #   description: 'Provide Region'     
    #   required: true
    #   default: 'ap-south-1'
    # project_name:
    #   description: 'Provide Project Name'     
    #   required: true
    #   default: 'project_name'

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: terraform_admin
    env: 
      TF_LOG: INFO
      TF_VAR_account_id: ${{ secrets.ACCOUNT_ID }}
      TF_VAR_region: ap-south-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE}}
    defaults:
      run:
        shell: bash
        working-directory: ./terraform
    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v2

      - name: Setup Terraform with specific version on the runner
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.2
        
      - name: Terraform Init
        id: init
        run: |
          # cd terraform
          terraform fmt
          terraform init \
           -backend-config="bucket=ivs-inspector-tfstate-test" \
           -backend-config="key=prod/ap-south-1/terraform.tfstate" \
           -backend-config="region=ap-south-1"

      - name: Terraform Validate
        id: validate
        run: |
          cd terraform
          terraform validate

      - name: Terraform Plan
        id: plan
        run: |
          cd terraform
          terraform plan -no-color -input=false
        continue-on-error: true

      - name: Terraform Apply
        id: apply
        if: github.ref == 'refs/heads/main'
        run: |
          cd terraform
          terraform destroy -auto-approve -input=false