name: AWS IVS Inspector Web

on: #workflow_dispatch
  push:
    branches:
      - main
env:
  TF_LOG: INFO
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: terraform_admin
    steps:
      - name: Checkout the repositoring to the runner
        uses: actions/checkout@v3

      - name: Install Amplify CLI
        run: |
          cd web-application
          npm install -g @aws-amplify/cli

      - name: Configure Amplify
        run: amplify configure  # This step might require some interactive setup

      - name: Deploy to Amplify
        run: amplify pull d2nmdzktuwpd59