name: AWS IVS Inspector Web

on: workflow_dispatch
      
env:
  TF_LOG: INFO
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: terraform_admin
    steps:
      - name: Checkout the repositoring to the runner
        uses: actions/checkout@v3
